#!/usr/bin/env bash



usage() {
cat<<EOF
$0 <build|run|run-config> [run-args]

Build or run the integration test docker image.

EOF
}

build() {
  mvn clean deploy \
    -DskipTests \
    -Dexec.skip=true \
    -Dsentinel.skipLaunch=true \
    -P'!standard' \
    -Prelease \
    -Ddocker.skip.push=true \
    -Dmaven.deploy.skip=true \
    -Ddocker.username=$DOCKER_USERNAME \
    -Ddocker.password="$DOCKER_PASSWORD"
}


run() {
  case $(uname) in
    Darwin) THIS_MACHINE="docker.for.mac.localhost";;
    Linux) THIS_MACHINE="localhost";;
    *) echo "Add support for your operating system: $(uname)"; exit 1;;
  esac
  docker run \
    --rm \
    --network="host" \
    -e VV_URL=http://$THIS_MACHINE \
    -e K8S_ENVIRONMENT=${ENV:-local} \
    -e SENTINEL_ENV=${ENV:-local} \
    vasdvp/lighthouse-veteran-verification-tests:latest $@
}

runConfig() {
  if [ -z "$VV_DU_PATH" ]; then echo "Variable VV_DU_PATH must be specified."; exit 1; fi
  case $(uname) in
    Darwin) THIS_MACHINE="docker.for.mac.localhost";;
    Linux) THIS_MACHINE="localhost";;
    *) echo "Add support for your operating system: $(uname)"; exit 1;;
  esac

  # comment for local testing
  URL=https://dev-api.va.gov/services

  docker run \
    --rm \
    --network="host" \
    -e VV_URL=${URL:-http://$THIS_MACHINE} \
    -e K8S_ENVIRONMENT=${ENV:-qa} \
    -e SENTINEL_ENV=${ENV:-qa} \
    --env-file ${VV_DU_PATH}/qa.testvars \
    vasdvp/lighthouse-veteran-verification-tests:latest $@
}

main() {
  local cmd=$1
  shift
  case "$cmd" in
    r|run) run $@;;
    rc|run-config) runConfig $@;;
    b|build) build;;
    br) build && run $@;;
    *) usage "Unknown command $cmd"
  esac
}


main $@
